// Step-by-step, verified lab tutorials for chapters 9-11, 16 and 17.
const PROG = "computer programming students (C track)";
const BOTH = "computer architecture and programming students (both tracks)";
const RUN = (f, p) => `$ labs/run.sh ${f} ${p}`;
const HOW = T("How every step works", ["Each step is a complete file in labs/: read what is new, then run it", "From the textbook folder: labs/run.sh STEP_FILE PREFIX builds and starts it",
  "Set PRG32_HOME to your PRG32 checkout; set PRG32_URL to run on a board or PRG32-QT, otherwise QEMU starts", "The screenshot on each slide is that exact file, built and executed", "After each step: change one thing, predict, run"]);

// ------------------------------------------------------------------ chapter 9
const L9 = "labs/09-c-first-contact/", E9 = (s) => `${L9}expected/${s}.png`;
Deck({ n: 9, slug: "c-first-contact", kind: "lab", title: "C Lab 1: Pong, One Function at a Time", short: "Functions, Variables, Game Loop",
  subtitle: "Six verified steps from three empty functions to a scoring game",
  audience: PROG, prep: "Working toolchain. Step files: labs/09-c-first-contact/step1..6 (master: labs/masters/pong_c.master.c).",
  goals: ["Build and run a C cartridge", "Keep state in file-scope variables and initialise it", "Move and clamp a paddle from the input mask", "Animate a ball and bounce it", "Use a function's result as a condition", "Count an event exactly once"],
  agenda: [["Skeleton", 6], ["State and draw", 8], ["Paddle", 8], ["Ball", 8], ["Collision", 8], ["Score", 7]],
  slides: [
    HOW,
    H("Skeleton", "Step 1"),
    K("Step 1: three empty functions", L9 + "step1_skeleton.c", null, ["prg32.h declares the runtime", "The prefix pong_c names the game", "No main: the runtime owns the loop"]),
    X("Run step 1", [RUN("09-c-first-contact/step1_skeleton.c", "pong_c"), "Read the build log: code= ?", "Rename pong_c_draw to pong_draw and build again", "Read the error; restore the name"], 5, "A black screen, code=2604: the same size as an empty assembly cartridge. With the wrong name the builder cannot find the draw entry point.", null, E9("step1_skeleton")),
    T("Why 2604 bytes for three empty functions", ["Your code is a few bytes", "The builder adds a stub for each of the 139 runtime functions", "A cartridge does not link against the C library", "No printf, no malloc: nothing is behind your file but prg32.h"], null, ["2604", "bytes, almost all stubs"]),
    H("State and draw", "Step 2"),
    W("Step 2: state, init, draw", L9 + "step2_state_draw.c", ["static int paddle_x;", 21], E9("step2_state_draw"), "Five file-scope variables are the whole game state. init sets them once; draw paints from them."),
    X("Run step 2", [RUN("09-c-first-contact/step2_state_draw.c", "pong_c"), "Change paddle_x in init to 0, then 256", "Move prg32_gfx_clear to the END of draw", "Restore it"], 6, "A white paddle and a yellow ball. With clear last, the screen is black: it paints over what was drawn.", null, E9("step2_state_draw")),
    Q("Why are the variables declared outside every function?", ["It is faster", "So that they keep their values between frames", "The compiler requires it", "So that other cartridges can read them"], 1, "File-scope variables live for the whole run; static keeps their names private to the file."),
    H("Paddle", "Step 3"),
    W("Step 3: input and clamp", L9 + "step3_paddle.c", ["void pong_c_update(void) {", 11], E9("step3_paddle"), "One call returns every button. & tests one bit. Two ifs keep paddle_x within 0..256."),
    X("Run step 3", [RUN("09-c-first-contact/step3_paddle.c", "pong_c"), "Hold RIGHT to the edge", "Change 3 to 8: does it still stop exactly at the edge?", "Replace & by == in the LEFT test; hold LEFT and A together"], 6, "The paddle stops at 256 at any speed, because the clamp runs after the move (screenshot: RIGHT for 30 frames, x = 218). With == the test fails as soon as a second button is held.", null, E9("step3_paddle")),
    H("Ball", "Step 4"),
    W("Step 4: velocity and bounce", L9 + "step4_ball.c", ["ball_x += ball_dx;", 8], E9("step4_ball"), "Position += velocity, every frame. || means or. A unary minus reverses direction at each wall."),
    X("Run step 4", [RUN("09-c-first-contact/step4_ball.c", "pong_c"), "Time one horizontal crossing", "Set ball_dx = 0 in init: predict, then run", "Set ball_dx = 5: watch the right edge closely"], 6, "About 5 seconds per crossing (312 pixels at 2 per frame). With 5 the ball can overshoot by a few pixels before turning: no clamp here.", null, E9("step4_ball")),
    H("Collision", "Step 5"),
    W("Step 5: one call, one decision", L9 + "step5_collision.c", ["if (ball_y < 0) {", 12], E9("step5_collision"), "The bottom no longer bounces: a miss restarts the round. The hitbox result is used directly as the condition."),
    X("Run step 5", [RUN("09-c-first-contact/step5_collision.c", "pong_c"), "Keep the ball alive for ten bounces", "Miss on purpose", "Change 'ball_dy = -1' to 'ball_dy = -ball_dy' and hit the ball with the paddle's side"], 6, "A real game. With negation the ball can jitter inside the paddle; assigning -1 is safe to repeat on every overlapping frame.", null, E9("step5_collision")),
    V("Assign or negate", ["ball_dy = -1;", ["Idempotent: doing it twice changes nothing", "Safe while the ball overlaps for several frames", "Fixes the speed"]], ["ball_dy = -ball_dy;", ["Flips on every overlapping frame", "Needs a guard: if (ball_dy > 0)", "Keeps the speed"]]),
    H("Score", "Step 6"),
    W("Step 6: count once", L9 + "step6_score.c", ["if (prg32_sprite_hitbox", 8], E9("step6_score"), "The ball may overlap the paddle for several frames. ball_dy > 0 is true only on the first: one hit, one point."),
    X("Run step 6", [RUN("09-c-first-contact/step6_score.c", "pong_c"), "Score five points: the bar is 20 pixels long", "Remove the 'if (ball_dy > 0)' around score += 1", "How fast does the bar grow now?"], 6, "+4 pixels per hit. Without the guard the bar jumps by several points per hit: every overlapping frame counts.", null, E9("step6_score")),
    Q("What does 'score * 4' as a rectangle width do when score is 0?", ["Crashes", "Draws nothing: a rectangle of width 0", "Draws a full-width bar", "Draws one pixel"], 1, "Verified: a zero-width rectangle draws nothing."),
    T("What you built", ["59 lines of C; 2952 bytes of cartridge", "Six variables of state", "update: input, paddle, ball, walls, collision, score", "draw: clear, paddle, ball, title, bar", "The assembly version of the same game is 139 lines"], null, ["59", "lines of C"]),
    N("You can now", ["Build and run a C cartridge", "Keep state at file scope", "Read input with & and clamp with if", "Animate with velocity", "Use a return value as a condition", "Guard a counter"]),
  ],
  next: ["Read Chapter 10: arrays, structs, tile maps", "Replace the repeated numbers with #define constants", "The next lab starts from this game"],
  refs: ["Textbook, Chapter 9", "labs/09-c-first-contact/ and labs/masters/pong_c.master.c", "PRG32 docs/learn/tutorial_c_game.md"] });

// ------------------------------------------------------------------ chapter 10
const L10 = "labs/10-c-structs-and-tiles/", E10 = (s) => `${L10}expected/${s}.png`;
Deck({ n: 10, slug: "c-structs-and-tiles", kind: "lab", title: "C Lab 2: Bricks, Then a World", short: "Arrays, Structs, Tile Maps",
  subtitle: "Part A adds an array of bricks in three steps; Part B builds a tile level and an actor in three more",
  audience: PROG, prep: "Step files in labs/10-c-structs-and-tiles: bricks_*_step1..3.c (prefix bricks_c) and plat_*_step1..3.c (prefix plat).",
  goals: ["Declare an array and loop over it to draw and to collide", "Recognise an out-of-bounds index", "Factor a repeated expression into a function", "Build a level from tiles and flags", "Drive an actor struct with the platform helpers"],
  agenda: [["Bricks: draw", 9], ["Bricks: hit and win", 12], ["World", 9], ["Actor", 9], ["Hazard", 6]],
  slides: [
    HOW,
    H("Part A: bricks", "An array and two loops"),
    W("A1: ten bricks, one loop", L10 + "bricks_draw_step1.c", ["void bricks_c_draw(void) {", 10], E10("bricks_draw_step1"), "bricks[i] is 1 while brick i is intact. One brick every 32 pixels: x = i * 32 + 2, 28 wide."),
    X("Run A1", [RUN("10-c-structs-and-tiles/bricks_draw_step1.c", "bricks_c"), "Count the bricks", "Change the loop test to i <= BRICKS", "What is bricks[10]?"], 5, "Ten cyan bricks; the ball passes through them. With <= the loop reads one byte past the array: whatever happens to follow it in memory. C did not stop you.", null, E10("bricks_draw_step1")),
    Q("uint8_t bricks[10]; what does 'bricks[10] = 0;' do?", ["Clears the last brick", "Writes one byte past the array", "Fails to compile", "Grows the array"], 1, "Valid indices are 0..9, and nothing checks."),
    W("A2: hitting a brick", L10 + "bricks_hit_step2.c", ["if (prg32_sprite_hitbox(ball_x, ball_y, 8, 8, paddle_x", 13], E10("bricks_hit_step2"), "The same hitbox call, in a loop. && short-circuits: a destroyed brick is never tested. break: one brick per frame."),
    X("Run A2", [RUN("10-c-structs-and-tiles/bricks_hit_step2.c", "bricks_c"), "Destroy three bricks", "Remove the 'break;'", "Aim the ball at the gap between two bricks"], 6, "Bricks vanish and the ball is sent down (screenshot: frame 120, one brick gone). Without break two adjacent bricks can go in one frame.", null, E10("bricks_hit_step2")),
    W("A3: one function owns the layout", L10 + "bricks_win_step3.c", ["static int brick_x(int i)", 1], E10("bricks_win_step3"), "The expression i * 32 + 2 appeared in draw and in update. Now it has a name, and the two cannot disagree."),
    K("A3: counting what is left", L10 + "bricks_win_step3.c", ["int intact = 0;", 7], ["A second loop sums the array", "0 intact: the row comes back", "A local variable: fresh every frame"]),
    X("Run A3", [RUN("10-c-structs-and-tiles/bricks_win_step3.c", "bricks_c"), "In brick_x change 32 to 30", "Do the picture and the collisions still agree?", "Clear the whole row"], 6, "Yes: one edit moved both. Clearing the row brings it back (screenshot: frame 300).", null, E10("bricks_win_step3")),
    H("Part B: a world", "Tiles, flags, an actor"),
    W("B1: a level from three runs", L10 + "plat_world_step1.c", ["static void fill_world(void) {", 7], E10("plat_world_step1"), "One 8-byte bitmap defines tile 2. put_run lays a horizontal run. Tile rows 22, 17, 12 are pixel rows 176, 136, 96."),
    X("Run B1", [RUN("10-c-structs-and-tiles/plat_world_step1.c", "plat"), "Add a fourth platform at tile row 8, columns 5 to 9", "Change the bitmap: 0xff in every byte", "Convert tile (10, 17) to pixels"], 5, "A ground line and platforms of outlined tiles. (10, 17) is pixel (80, 136): multiply by 8.", null, E10("plat_world_step1")),
    G("The playfield in numbers", ["Quantity", "Value"], [["Tile size", "8 x 8 pixels"], ["Grid", "64 x 32 tiles = 512 x 256 pixels"], ["Layers", "2"], ["Bytes for one layer", "2048"], ["Screen", "40 x 25 tiles visible"]], "A level is 2 KiB of tile numbers, not 128 KiB of pixels."),
    W("B2: an actor in the world", L10 + "plat_actor_step2.c", ["void plat_update(void) {", 8], E10("plat_actor_step2"), "One struct holds position, velocity, size and state. &player passes its address so the helper can change it."),
    X("Run B2", [RUN("10-c-structs-and-tiles/plat_actor_step2.c", "plat"), "Walk right and jump with A", "Remove the prg32_platform_tile_flags line in init", "What happens to the player?"], 6, "The player walks, jumps and lands; the view scrolls (screenshot: RIGHT held, one jump). Without the SOLID flag the player falls through: a tile number has no behaviour until it is flagged.", null, E10("plat_actor_step2")),
    M("prg32_platform_actor_t in memory", [["x", 4, "int: position"], ["y", 4, "int"], ["vx", 4, "int: velocity"], ["vy", 4, "int"], ["w", 2, "uint16_t: size"], ["h", 2, "uint16_t"], ["state", 2, "uint16_t: flags set by the physics step"], ["layer, reserved", 2, "two uint8_t"]],
      "24 bytes. The assembly track reaches the same fields as offsets from one base address: PRG32_PLATFORM_ACTOR_X_OFFSET is 0, ..._STATE_OFFSET is 20."),
    W("B3: a hazard", L10 + "plat_hazard_step3.c", ["if (state & PRG32_PLATFORM_HAZARD) {", 4], E10("plat_hazard_step3"), "The physics step returns flags in one integer. & tests one of them, exactly like a button."),
    X("Run B3", [RUN("10-c-structs-and-tiles/plat_hazard_step3.c", "plat"), "Walk into the red spikes", "Jump over them", "Flag tile 5 as SOLID | HAZARD instead"], 6, "Touching the spikes plays a low note and returns the player to the start (screenshot: just before contact).", null, E10("plat_hazard_step3")),
    Q("The player falls through the ground. First thing to check?", ["Gravity", "That the ground tile id is flagged SOLID", "The tile's colour", "The camera"], 1, "The map stores numbers; flags give them behaviour."),
    T("Review", ["Where did an array remove repetition?", "What did brick_x protect you from?", "What does &player let the helper do?", "Which numbers were in tiles and which in pixels?"]),
    N("You can now", ["Loop over an array to draw and to collide", "Spot an out-of-bounds index", "Give a repeated expression a name", "Build a level from tiles and flags", "Use a struct with the platform helpers"]),
  ],
  next: ["Add coins: PRG32_TILE_FLAG_COLLECT and PRG32_PLATFORM_COLLECT", "Read Chapter 11", "Compare with examples/games/platformer/c/game.c"],
  refs: ["Textbook, Chapter 10", "labs/10-c-structs-and-tiles/ in the textbook repository", "PRG32 docs/software/framework_manual.md"] });

// ------------------------------------------------------------------ chapter 11
const L11 = "labs/11-c-capstone/", E11 = (s) => `${L11}expected/${s}.png`;
Deck({ n: 11, slug: "c-capstone", kind: "lab", title: "C Lab 3: Refactor, Refine, Ship", short: "C Capstone",
  subtitle: "Four verified steps: named constants and a helper, fixed-point motion, lives and edges, a submitted score",
  audience: PROG, prep: "Step files: labs/11-c-capstone/step1..4 (prefix refine_c). Step 1 behaves exactly like the end of C Lab 1.",
  goals: ["Refactor without changing behaviour", "Use Q8 fixed point for position and velocity", "Avoid integer-division traps", "Detect button edges; manage lives and game over", "Submit a score exactly once", "Ship and document a cartridge"],
  agenda: [["Refactor", 9], ["Fixed point", 12], ["Lives and edges", 11], ["Score", 6], ["Ship", 7]],
  slides: [
    HOW,
    H("Refactor", "Step 1: same behaviour, better code"),
    W("Step 1: names and a helper", L11 + "step1_refactor.c", ["static int clamp(int value", 5], E11("step1_refactor"), "clamp replaces four ifs. Constants replace 64, 188, 8; limits become visible computations."),
    X("Run step 1", [RUN("11-c-capstone/step1_refactor.c", "refine_c"), "Play: it must behave exactly like C Lab 1", "Change PADDLE_W to 32", "Check picture, limit and collision"], 5, "Identical behaviour; with 32 the paddle, its right limit and its hitbox all follow from one edit.", null, E11("step1_refactor")),
    Q("Why is clamp declared static?", ["To keep its value between calls", "To keep the name private to this file", "To make it faster", "Helpers must be static"], 1, "On a function, static limits linkage."),
    H("Fixed point", "Step 2: speeds between whole pixels"),
    G("Q8 at a glance", ["Real value", "Stored integer", "How"], [["1.0", "256", "value * Q"], ["1.5", "384", "3 * Q / 2"], ["0.25", "64", "Q / 4"], ["back to pixels", "v / 256", "divide by Q"]], "Q = 256: eight fractional bits. Positions and velocities share the scale, so adding them needs no conversion."),
    W("Step 2: the ball in Q8", L11 + "step2_fixed_point.c", ["ball_xq += ball_dxq;", 12], E11("step2_fixed_point"), "Limits are compared in Q units; only the hitbox and draw divide by Q. Each hit multiplies the speed by 21/20."),
    X("Run step 2", [RUN("11-c-capstone/step2_fixed_point.c", "refine_c"), "Time one crossing: 312 pixels at 1.5 per frame", "Set ball_dxq = Q / 4 in init: what do you see?", "Change '* 21 / 20' to '* (21 / 20)'"], 7, "208 frames, about 7 seconds. At 0.25 the ball moves one pixel every fourth frame. (21 / 20) is integer division: 1, so the speed-up vanishes.", null, E11("step2_fixed_point")),
    T("Integer traps", ["21 / 20 is 1; 3 / 2 is 1", "Multiply first, divide last: x * 21 / 20", "x * 21 must fit in 32 bits before the division", "Never add a Q8 value to a plain pixel count"], null, ["3 * Q / 2", "= 384, not 256"]),
    Q("In Q8, what is stored for 2.75?", ["275", "704", "2.75", "11"], 1, "2.75 * 256 = 704."),
    H("Lives and edges", "Step 3"),
    W("Step 3: edges, and game over", L11 + "step3_lives.c", ["uint32_t pressed", 9], E11("step3_lives"), "pressed has a bit set only in the frame a button goes down. While game_over, update does nothing but wait for that edge."),
    K("Step 3: losing a life", L11 + "step3_lives.c", ["/* missed */", 9], ["A low note on a miss", "serve() restarts the ball only", "At zero lives: game_over = 1", "Runs once: the ball is re-served"]),
    X("Run step 3", [RUN("11-c-capstone/step3_lives.c", "refine_c"), "Lose three balls without moving", "Press A once to restart", "Change 'pressed & PRG32_BTN_A' to 'input & PRG32_BTN_A' and hold A through a game over"], 7, "Three squares count the lives; then GAME OVER (screenshot: no input for 700 frames). With the level instead of the edge, holding A restarts instantly and you never see the message.", null, E11("step3_lives")),
    H("Score", "Step 4"),
    W("Step 4: submit once", L11 + "step4_score_submit.c", ["if (lives == 0) {", 4], E11("step4_score_submit"), "The call sits where game_over becomes 1: a place that executes exactly once per game."),
    X("Run step 4", [RUN("11-c-capstone/step4_score_submit.c", "refine_c"), "Play a game to the end", "Open the scoreboard in the device's setup menu", "Where would the call be WRONG, and what would you see?"], 5, "One entry for refine-pong under the configured player name. Inside 'if (game_over)' at the top of update it would be submitted 30 times a second."),
    H("Ship", "A file and a note"),
    X("Build and inspect by hand", ["$ cd $PRG32_HOME", "$ python3 -m prg32 cartridge build ../Playing-with-RISC-V_PRG32_textbook/labs/11-c-capstone/step4_score_submit.c --portable --entry-prefix refine_c --name refine-pong --out work/refine-pong.prg32", "$ python3 -m prg32 cartridge summary work/refine-pong.prg32"], 5, "code=3280 mem=3316: 36 bytes of variables that start at zero (.bss). About 5% of the 64 KiB budget."),
    G("How the cartridge grew", ["Step", "code", "mem", "What was added"], [["1 refactor", "2908", "2932", "baseline"], ["2 fixed point", "2968", "2992", "+60: Q8 arithmetic"], ["3 lives", "3248", "3284", "+280: edges, game over, text, notes"], ["4 score", "3280", "3316", "+32: one call"]], "Real sizes from the build logs."),
    X("Write the design note", ["One sentence: what the game is", "A table: each state variable and what changes it", "The helpers you have and why", "One thing you would do next"], 5, "Half a page from which a classmate can understand the source in five minutes."),
    N("You can now", ["Refactor safely", "Move and accelerate with fixed point", "Use edges for one-shot actions", "Place a once-only action correctly", "Read a cartridge's size budget"]),
  ],
  next: ["Read Chapter 16: what the compiler did with this C", "Read Chapter 17 if you intend to publish", "Hand in the design note with the cartridge"],
  refs: ["Textbook, Chapter 11", "labs/11-c-capstone/ and labs/masters/refine_c.master.c", "PRG32 docs/cartridge_store/score_api.md"] });

// ------------------------------------------------------------------ chapter 16
const L16 = "labs/16-assembly-meets-c/";
const GCC = (o) => `$ riscv32-esp-elf-gcc -S -${o} -march=rv32imac -mabi=ilp32 -Icomponents/prg32/include -Icomponents/prg32_audio/include ../Playing-with-RISC-V_PRG32_textbook/labs/09-c-first-contact/step6_score.c -o work/pong_${o}.s`;
Deck({ n: 16, slug: "assembly-meets-c", kind: "lab", title: "Reunion Lab: Read What the Compiler Wrote", short: "Assembly Meets C",
  subtitle: "Compile the C Pong of C Lab 1 to assembly at two optimisation levels and read the real output",
  audience: BOTH, prep: "Toolchain active, working directory $PRG32_HOME. Reference listings (the real compiler output) are in labs/16-assembly-meets-c/.",
  goals: ["Generate assembly from C at -O0 and -Os", "Find a C statement in compiler output", "Read a compiler-generated frame", "Explain what optimisation changed, with counts", "Compare compiled and hand-written code fairly"],
  agenda: [["Generate", 7], ["Read -O0", 13], ["Read -Os", 12], ["Compare", 8], ["In the debugger", 5]],
  slides: [
    T("Attitude for this lab", ["You are reading, not writing", "The compiler's output is correct: your job is to understand it", "The same source, compiler and flags give the same output: compare with the slides", "Unknown instruction? Look it up and write it down"]),
    H("Generate", "C in, assembly out"),
    X("Compile without optimisation", ["$ cd $PRG32_HOME && mkdir -p work", GCC("O0"), "$ wc -l work/pong_O0.s"], 4, "223 lines of assembly for 59 lines of C."),
    X("Compile for size", [GCC("Os"), "$ wc -l work/pong_O0.s work/pong_Os.s", "Find the label pong_c_update in both"], 3, "192 lines at -Os against 223 at -O0. The update function alone: 83 lines against 114."),
    H("Read -O0", "A literal translation"),
    K("pong_c_update at -O0: frame and first if", L16 + "pong_c_update_O0.s", ["pong_c_update:", 15], ["32-byte frame; ra and s0 saved", "s0 becomes a frame pointer", "input is stored at -20(s0)...", "...and immediately reloaded", "paddle_x: load, add -3, store"], "Real output of riscv32-esp-elf-gcc -O0 for labs/09-c-first-contact/step6_score.c."),
    X("Match C to assembly", ["Open work/pong_O0.s beside step6_score.c", "Find the instructions for: uint32_t input = prg32_input_read();", "Find: if (input & PRG32_BTN_LEFT)", "Find: paddle_x -= 3;"], 6, "call + sw a0,-20(s0); then lw, andi a5,a5,1, beq; then lui/lw, addi a4,a5,-3, lui/sw."),
    G("Line by line", ["C", "-O0 assembly"], [["input = prg32_input_read();", "call prg32_input_read / sw a0,-20(s0)"], ["input & PRG32_BTN_LEFT", "lw a5,-20(s0) / andi a5,a5,1"], ["if (...) {", "beq a5,zero,.L3"], ["paddle_x -= 3;", "lui+lw / addi a4,a5,-3 / lui+sw"]], null, [1.2, 1.8]),
    T("What %hi and %lo mean", ["An address is 32 bits; an instruction has room for 20 or 12", "lui loads the upper 20 bits: %hi(paddle_x)", "The load or store adds the lower 12: %lo(paddle_x)", "Your hand-written 'la' expands to the same idea"]),
    X("Count the memory traffic", ["In the -O0 update, count loads (lw) and stores (sw) up to label .L4", "How many times is 'input' reloaded from the stack?", "How many times is paddle_x loaded?"], 5, "input is stored once and reloaded for each test; paddle_x is loaded and stored separately in each if. Every statement stands alone."),
    Q("Why does -O0 store input and reload it at once?", ["A compiler bug", "Without optimisation every variable lives in memory", "The ABI requires it", "For alignment"], 1, "Simple and easy to debug, not efficient."),
    H("Read -Os", "The same program, rearranged"),
    K("pong_c_update at -Os", L16 + "pong_c_update_Os.s", ["pong_c_update:", 20], ["Still a frame: the function calls others", "No frame pointer; s0-s3 saved for reuse", "input stays in a0: never stored", "The address of paddle_x is kept in s0", "Each if: lw, addi, sw"], "Real output at -Os."),
    X("What changed?", ["Find where 'input' lives now", "Count the lui instructions for paddle_x in the first three ifs", "Which registers hold values across the hitbox call?", "Why s registers?"], 6, "input is used straight from a0. One lui, kept in s0. Values that must survive calls are in s registers, exactly as you did by hand."),
    G("Three versions of update", ["", "Hand-written", "gcc -O0", "gcc -Os"], [["Lines (update only)", "74", "114", "83"], ["Variables live in", "registers you chose", "memory, always", "registers where possible"], ["Frame pointer", "no", "yes (s0)", "no"], ["Mirrors the source", "yes", "yes", "less"]], "The hand-written count is labs/07-asm-graphics-game/step6_collision.S, update only."),
    Q("The -Os code keeps the address of paddle_x in s0 rather than t0. Why?", ["s0 is faster", "It must survive the calls that follow", "t0 is reserved", "By accident"], 1, "Callee-saved registers survive calls; the compiler saves s0 in its prologue for that purpose."),
    H("Compare", "A fair comparison"),
    X("Build both as cartridges", ["From the textbook folder (the builder compiles C with -Os):", "$ labs/run.sh 09-c-first-contact/step6_score.c pong_c", "$ labs/run.sh 08-asm-capstone/step7_score.S pong", "Note code= for each"], 5, "2952 bytes for C, 3052 for the hand-written assembly: within a few percent, and both mostly stubs."),
    T("What the numbers say", ["A modern compiler at -Os matches careful hand-written code on a game this size", "It found the same idea: keep addresses and inputs in registers that survive calls", "Your version has names, comments and structure a compiler does not write", "Read -O0 to learn the mapping; read -Os to learn the tricks"]),
    X("One thing each way", ["Find one thing the compiler did that you did not think of", "Find one thing your assembly does more clearly", "Write both down with the line numbers"], 4, "For example: the compiler reuses one loaded address for several statements; your file has labels that say what each block is for."),
    H("In the debugger", "Compiled code is just code"),
    X("Step through compiled code", ["Build step6_score.c as a cartridge and import it into PRG32-QT, debug mode", "Select Update; step past the trampoline into pong_c_update", "Step to just after the first jump through a stub", "Hold LEFT, repeat, and read a0"], 5, "a0 = 1 with LEFT held. The instructions you step are the -Os listing you just read."),
    N("You can now", ["Produce assembly from C at two levels", "Find statements in compiler output", "Read %hi/%lo, frames and saved registers", "Explain optimisation with counts", "Compare compiled and hand-written code"]),
  ],
  next: ["Write one page: three things the compiler did for me", "Read Chapter 17 and prepare a bundle", "Optional: Appendix B, measure both cartridges on a board"],
  refs: ["Textbook, Chapter 16", "labs/16-assembly-meets-c/ (reference listings)", "GCC manual: optimisation options", "RISC-V ELF psABI"] });

// ------------------------------------------------------------------ chapter 17
const SS = "scripts/store/";
Deck({ n: 17, slug: "cartridge-store", kind: "lab", title: "Publishing Lab: Submit, Review, Download", short: "The Cartridge Store",
  subtitle: "A complete, reproducible publishing cycle on a classroom Store, with the real replies of every command",
  audience: BOTH + ", teachers, and Store staff", prep: "A classroom Cartridge Store (docker compose up, or python app.py with SECRET_KEY set) on the lab network; default admin password changed. Every command and reply on these slides was run against a local Store.",
  goals: ["Register and create a publication token", "Build, describe, pack and submit a bundle", "Review a submission and see what an editor cannot change", "Download as a visitor and run the game", "Post a score and read the scoreboard", "Optional: run a Store of your own"],
  agenda: [["Account and token", 7], ["Build and describe", 10], ["Submit", 6], ["Review", 9], ["Visitor and scores", 7], ["Your own Store", 6]],
  slides: [
    T("Roles in this lab", ["You start as a registered user and submit a game", "Then you are editor for a neighbour's submission", "Then a visitor, downloading what was published", "$ export PRG32_STORE_URL=http://STORE-ADDRESS:5080"]),
    H("Account and token", "Registered user"),
    X("Register and log in", ["Open the Store in a browser; choose Register", "Enter your e-mail; follow the verification link; set a password", "Log in: Publish and Tokens appear in the navigation bar"], 4, "A logged-in session. Without SMTP on the Store, the instructor reads the link from the server log."),
    X("Create a publication token", ["Open Tokens; label: your machine's name", "Create token and copy it now: it is shown once", "$ export PRG32_STORE_TOKEN=prg32_...   (in the shell, not in a file)", "$ curl -H \"Authorization: Bearer $PRG32_STORE_TOKEN\" $PRG32_STORE_URL/auth/me"], 4, "/auth/me answers with \"authenticated\": true and your username."),
    Q("Where should the token be stored?", ["In manifest.json", "In the Git repository", "In an environment variable or a secrets manager", "In the cartridge"], 2, "Revoke and recreate it if it leaks."),
    H("Build and describe", "One game, two variants, one manifest"),
    K("Build both variants", SS + "build_variants.sh", null, ["Run from $PRG32_HOME", "First copy examples/complete/lemon_catcher_c_game.c to work/", "Two files in build/store-lemon/"]),
    X("Build", ["$ cd $PRG32_HOME && mkdir -p work && cp ../Playing-with-RISC-V_PRG32_textbook/examples/complete/lemon_catcher_c_game.c work/", "Run the loop from the previous slide", "$ ls -l build/store-lemon"], 5, "lemon-catcher-esp32c6.prg32 and lemon-catcher-qemu.prg32, 3432 bytes each."),
    K("The manifest", "examples/store_publishing/manifest.json", null, ["Change id, authors, summary", "File names must match the two cartridges", "assets.icon names a PNG beside it"]),
    X("Describe", ["$ cp ../Playing-with-RISC-V_PRG32_textbook/examples/store_publishing/manifest.json build/store-lemon/", "$ cp ../Playing-with-RISC-V_PRG32_textbook/examples/store_publishing/icon.png build/store-lemon/", "Edit the manifest: set \"id\" to org.example.YOURNAME.lemon and your name in authors"], 5, "Four files in build/store-lemon: manifest.json, icon.png and two cartridges. The id must be unique in the Store."),
    H("Submit", "Into the review queue"),
    X("Pack the bundle", ["$ python3 -m prg32 store pack-bundle --manifest build/store-lemon/manifest.json --out build/lemon-catcher-1.0.0.zip", "$ unzip -l build/lemon-catcher-1.0.0.zip"], 3, "A ZIP of four files, 7752 bytes of content: manifest.json 603, icon.png 285, two cartridges of 3432."),
    X("Publish it", ["$ python3 -m prg32 store publish-bundle build/lemon-catcher-1.0.0.zip --store-url $PRG32_STORE_URL --token $PRG32_STORE_TOKEN", "Read the reply", "Search for your game in the Store's web page"], 3, "The tool lists the two architectures and ends with 'Submitted for review'. The game is NOT in the catalogue yet."),
    K("What publish-bundle prints", "[\n  {\n    \"architecture\": \"esp32c6\",\n    \"file\": \"lemon-catcher-esp32c6.prg32\"\n  },\n  {\n    \"architecture\": \"qemu\",\n    \"file\": \"lemon-catcher-qemu.prg32\"\n  }\n]\nSubmitted for review", null, ["One entry per variant", "Pending: an editor must verify it"], "Output captured from a real run."),
    H("Review", "Editor: your neighbour's submission"),
    X("See the queue", ["The instructor adds you to the editors group; log out and in", "Open Review in the browser, or:", "$ curl -H \"Authorization: Bearer $PRG32_STORE_TOKEN\" $PRG32_STORE_URL/api/submissions"], 3, "A list of pending submissions, each with an id, its metadata and where its two files are stored (pending/N/esp32c6.prg32, pending/N/qemu.prg32)."),
    X("Try to change what you may not", ["Take the submission number N of your neighbour's game", "$ curl -X POST $PRG32_STORE_URL/api/submissions/N/verify -H \"Authorization: Bearer $PRG32_STORE_TOKEN\" -H 'Content-Type: application/json' -d '{\"metadata\":{\"id\":\"x.y\"}}'"], 3, "{\"error\": \"metadata.id cannot be changed during review\", \"ok\": false}. Identity belongs to the author."),
    X("Review, then decide", ["Ask the author for the qemu variant and play it for two minutes", "Write: what it does; one thing that works; one thing to change", "$ curl -X POST $PRG32_STORE_URL/api/submissions/N/verify -H \"Authorization: Bearer $PRG32_STORE_TOKEN\" -H 'Content-Type: application/json' -d '{\"metadata\":{\"tags\":[\"class\",\"arcade\"]}}'"], 6, "\"ok\": true and the submission record. The game is now public, with the tags you set."),
    G("What an editor may edit", ["Editable", "Preserved from the package"], [["title, summary, description", "id"], ["tags", "version"], ["license, homepage, repository", "authors"]]),
    H("Visitor and scores", "No credentials needed to get games"),
    X("List and download", ["$ python3 -m prg32 store list --store-url $PRG32_STORE_URL", "$ curl -o lemon.prg32 \"$PRG32_STORE_URL/api/games/org.example.lemon-catcher/download?version=1.0.0&architecture=qemu\"", "$ ls -l lemon.prg32 && python3 -m prg32 store inspect-metadata lemon.prg32"], 5, "The list shows id, title and 'esp32c6, qemu'. The downloaded file is 4418 bytes, not 3432: the Store appended a metadata trailer with the manifest and the icon."),
    K("What store list prints", "ID                               Title                    Version  Architectures\norg.example.lemon-catcher        Lemon Catcher                     esp32c6, qemu", null, ["Public: no token was used", "One row per game"], "Output captured from a real run."),
    X("Post a score and read it back", ["$ curl -X POST $PRG32_STORE_URL/api/scores -H \"Authorization: Bearer $PRG32_STORE_TOKEN\" -H 'Content-Type: application/json' -d '{\"game\":\"lemon-catcher\",\"player\":\"Ada\",\"score\":42}'", "$ curl \"$PRG32_STORE_URL/api/scores?game=lemon-catcher\""], 4, "{\"ok\": true}, then a list with game, player, score 42 and submitted_by: your username. Posting needs a token; reading does not."),
    H("Your own Store", "Administrator, optional"),
    K("First deployment", SS + "admin_deploy.sh", null, ["SECRET_KEY is required", "Data persists in ./data", "The health check is the discovery document"]),
    X("Stand one up", ["Run the deployment commands on your laptop", "$ curl http://127.0.0.1:5080/.well-known/prg32-store.json", "Log in as admin and change the password at once", "Open Setup: give the Store a name"], 5, "The discovery document lists the service URLs and the roles reader, user, player, publisher, admin. The default administrator is in the editors group."),
    N("You can now", ["Create and protect a publication token", "Build, pack and submit a bundle", "Review a submission and know an editor's limits", "Use the Store without credentials", "Post and read scores", "Start a Store of your own"]),
  ],
  next: ["Revoke your lab token on shared machines", "Publish version 1.0.1 with your reviewer's suggestion", "Add the Store page to your coursework report"],
  refs: ["Textbook, Chapter 17", "scripts/store/ and examples/store_publishing/", "CartridgeStore docs/getting_started.md and api.md", "PRG32 docs/usage/tooling.md (store commands)"] });
