// Step-by-step, verified lab tutorials for chapters 3-8.  These replace the
// earlier lab decks.  Every step file under labs/ is a complete program that
// was built and executed; the screenshots on the slides are its real output.
const ARCH = "computer architecture students (RISC-V assembly track)";
const UNI = "first-year computer architecture and programming students";
const RUN = (f, p) => `$ labs/run.sh ${f} ${p}`;
const HOW = T("How every step works", ["Each step is a complete file in labs/: read what is new, then run it", "From the textbook folder: labs/run.sh STEP_FILE PREFIX builds and starts it",
  "Set PRG32_HOME to your PRG32 checkout; set PRG32_URL to run on a board or PRG32-QT, otherwise QEMU starts", "The screenshot on each slide is that exact file, built and executed", "After each step: change one thing, predict, run"]);

// ------------------------------------------------------------------ chapter 3
const L3 = "labs/03-setup/", E3 = (s) => `${L3}expected/${s}.png`;
Deck({ n: 3, slug: "setup", kind: "lab", title: "Setup Lab: From Empty Shell to Running Cartridge", short: "Development Environment",
  subtitle: "A reproducible walk from an activated toolchain to a cartridge you wrote, built, inspected and ran",
  audience: UNI, prep: "ESP-IDF 5.4 installed beforehand (20-40 minutes). The textbook repository cloned next to PRG32. Reference files: labs/03-setup/step1..3.",
  goals: ["Activate ESP-IDF and verify it with doctor", "Build and start the QEMU firmware", "Write, build, inspect and run a cartridge in three steps", "Read the build log and the cartridge summary", "Recognise the failure caused by an unsaved return address"],
  agenda: [["Verify the environment", 8], ["Emulator firmware", 9], ["Hello world in three steps", 16], ["Inspect", 5], ["Break it on purpose", 7]],
  slides: [
    T("Rules of the bench", ["Type the commands; read every line of output", "When something fails, read the FIRST error", "Each step ends with something you can see", "Write down every number the tools print"]),
    H("Verify the environment", "Nothing else works until this does"),
    X("Activate ESP-IDF", ["Open a new terminal (Windows: the ESP-IDF PowerShell)", "$ . $HOME/esp-idf/export.sh", "$ idf.py --version", "$ riscv32-esp-elf-gcc --version"], 3, "ESP-IDF v5.4 or newer, and a GCC whose target is riscv32-esp-elf."),
    X("Get PRG32 and run the doctor", ["$ git clone https://github.com/riscv-prg32/PRG32 && cd PRG32", "$ pip install pyaudio zeroconf", "$ export PRG32_HOME=$PWD", "$ python3 -m prg32 doctor"], 5, "Four [OK] lines, as on the next slide. Any [FAIL] means ESP-IDF is not active in this shell."),
    K("What doctor prints", "[OK] idf.py found\n[OK] riscv32-esp-elf-gcc found\n[OK] partitions file found: ~/PRG32/profiles/partitions_prg32.csv\n[OK] partition cart0 parsed (offset=0x210000, size=131072)", null,
      ["The build system", "The RISC-V cross-compiler", "The flash layout", "Slot cart0: 131072 bytes = 128 KiB of flash"], "Output captured from a real run."),
    Q("doctor reports that riscv32-esp-elf-gcc is missing. Most likely?", ["The repository is corrupted", "ESP-IDF is not active in this shell", "QEMU is not installed", "The cartridge is too large"], 1, "Source export.sh again."),
    H("Emulator firmware", "The real firmware on an emulated chip"),
    X("Build and start QEMU", ["$ python3 -m prg32 qemu build", "$ python3 -m prg32 qemu run", "Click the TERMINAL, then press the arrow keys", "Find Run Cartridge in the setup menu; press X to go back"], 9,
      "A build-qemu directory with qemu_flash.bin, then a window with the PRG32 screen. The terminal logs 'prg32_main: PRG32 runtime initialized'. Keys work only while the terminal has focus.", "The first build takes several minutes: use the time for the next two slides."),
    T("If the QEMU build stops at esp_crt_bundle.h", ["Seen on PRG32 main (a8669e5) with ESP-IDF v5.4, when building from a fresh clone", "Error: prg32_store.c: fatal error: esp_crt_bundle.h: No such file or directory", "Cause: the prg32 component does not list mbedtls for the QEMU target", "Fix: in components/prg32/CMakeLists.txt add the line 'mbedtls' after 'spi_flash' in PRG32_PRIV_REQUIRES", "Run the build again; it continues from where it stopped"],
      "Verified while preparing this lab: with that one line the build completes and QEMU boots. Remove this slide once the fix is upstream."),
    G("Keys in QEMU", ["PRG32 control", "Key"], [["Joystick", "Arrow keys or W A S D"], ["A (confirm)", "Z or J"], ["B (back)", "X or K"], ["Start / Select", "Enter or Space"]], "QEMU reads the keyboard from the terminal that launched it, not from the screen window."),
    HOW,
    H("Hello world in three steps", "Skeleton, text, more text"),
    K("Step 1: the skeleton", L3 + "step1_skeleton.S", null, [".global exports the three entry points", "Each function returns at once", "This is already a valid cartridge"]),
    X("Build it by hand, once", ["$ mkdir -p work/hello && cp ../Playing-with-RISC-V_PRG32_textbook/labs/03-setup/step1_skeleton.S work/hello/hello.S", "$ python3 -m prg32 cartridge build work/hello/hello.S --portable --entry-prefix hello_world --name hello --out work/hello/hello.prg32",
      "$ python3 -m prg32 qemu upload work/hello/hello.prg32 && python3 -m prg32 qemu run"], 5, "[OK] built ... code=2604 mem=2604, then a black screen: the runtime is calling three functions that return.", "Adjust the copy path to where the textbook repository is. Close QEMU before every upload.", E3("step1_skeleton")),
    K("Reading the build log", "[INFO] Portable: True\n[INFO] Building cartridge: work/hello/hello (Prefix: hello_world)\n[INFO] Cartridge RAM limit: 65536 bytes (default firmware profile)\n[OK] built work/hello/hello.prg32 name=hello load=0x40800000\n[INFO] code=2664 mem=2664 audio=0", null,
      ["Portable: calls go through the ABI table", "The limit of the 64 KiB profile", "Load address of every cartridge", "Sizes in bytes (this is step 2)"], "Output captured from a real build of step 2."),
    T("Why an empty cartridge is 2604 bytes", ["Your three functions are 3 instructions", "The builder adds one small stub per runtime function: 139 of them", "Each stub loads the ABI table and jumps to its entry", "Plus three entry trampolines that save the table pointer", "So every cartridge starts at about 2.6 KiB"], null, ["2604", "bytes: stubs and trampolines"]),
    W("Step 2: text on the screen", L3 + "step2_text.S", ["hello_world_draw:", 15], E3("step2_text"), "draw now calls two functions, so it saves ra. Five arguments in a0..a4: x, y, string address, foreground, background."),
    X("Run step 2", [RUN("03-setup/step2_text.S", "hello_world"), "Copy the new lines into your work/hello/hello.S and build it yourself", "Change x and y of the text", "Change CYAN to 0xF800"], 6, "HELLO WORLD in cyan at (32, 40); then where and in the colour you chose. code=2664: 60 bytes more than the skeleton.", null, E3("step2_text")),
    W("Step 3: a second line", L3 + "step3_two_lines.S", ["call prg32_gfx_text8", 8], E3("step3_two_lines"), "The same five-argument pattern again, 24 pixels lower, with a second string in .rodata."),
    X("Run step 3", [RUN("03-setup/step3_two_lines.S", "hello_world"), "Add a third line of your own at y = 88", "Give it a colour you computed in RGB565"], 5, "Two lines, then three. Each extra call costs about 60 bytes: check code= in the log.", null, E3("step3_two_lines")),
    H("Inspect", "What the firmware will read"),
    X("Read the summary", ["$ python3 -m prg32 cartridge summary work/hello/hello.prg32", "Find header_size, code_size, mem_size", "Find import_model and abi_hash", "Convert load_addr 1082130432 to hexadecimal"], 5,
      "header_size 100, code_size about 2724, import_model \"abi-table\", abi_hash \"0x260f6136\", flags 4. 1082130432 = 0x40800000."),
    G("The summary, field by field", ["Field", "Value here", "Meaning"], [["header_size", "100", "bytes before the code"], ["code_size / mem_size", "2724 / 2724", "code+data, and with .bss"], ["import_model", "abi-table", "portable cartridge"], ["abi_hash", "0x260f6136", "the table it was built for"],
      ["flags", "4", "bit 2: uses the ABI table"], ["load_addr", "0x40800000", "start of cartridge RAM"]], "Values from a real build of step 3."),
    H("Break it on purpose", "Learn the symptom while you know the cause"),
    X("The unsaved return address", ["In your hello.S delete 'sw ra, 12(sp)' and 'lw ra, 12(sp)' in draw", "Predict what happens at draw's ret", "Build and run", "Restore the two lines"], 5,
      "The cartridge never finishes a frame: draw returns into itself. QEMU freezes; PRG32-QT stops it and reports 'instruction budget exhausted'.", "Verified: the headless PRG32-QT runner prints 'frame 0: instruction budget exhausted'."),
    Q("Why does draw return into itself?", ["The stack overflowed", "call overwrote ra with an address inside draw, and ret jumps to ra", "The string was too long", "QEMU has a bug"], 1, "The original return address was never saved, so it was lost at the first call."),
    N("You can now", ["Verify a toolchain with doctor", "Build, upload and run a cartridge by hand", "Read the build log and the summary", "Explain why the smallest cartridge is 2.6 KiB", "Recognise an unsaved ra by its symptom"]),
  ],
  next: ["Keep work/hello: it is your scratch cartridge", "Install PRG32-QT for the next lab", "Assembly track: Chapter 5. C track: Chapter 9"],
  refs: ["Textbook, Chapter 3", "labs/03-setup/ in the textbook repository", "PRG32 docs/usage/getting_started.md and troubleshooting.md"] });

// ------------------------------------------------------------------ chapter 4
const L4 = "labs/04-prg32qt/probe.S", E4 = "labs/04-prg32qt/expected/probe.png";
Deck({ n: 4, slug: "prg32qt", kind: "lab", title: "Debugger Lab: Watch a Register Change", short: "PRG32-QT",
  subtitle: "A cartridge written to be watched: breakpoints, single steps, registers and memory, with known answers",
  audience: UNI, prep: "PRG32-QT installed; toolchain active. Source: labs/04-prg32qt/probe.S (65 lines). Build it once: labs/run.sh is not needed here.",
  goals: ["Build and import a cartridge into PRG32-QT", "See the entry trampoline the builder adds", "Stop after a call and read its result in a0", "Follow a branch decision", "Find a variable's address and watch its bytes change", "Control the debugger from the command line"],
  agenda: [["Build and import", 7], ["The trampoline", 8], ["Input in a0", 10], ["Memory", 11], ["Scripted control", 9]],
  slides: [
    T("The cartridge we will watch", ["probe.S: 65 lines, three variables", "frames: +1 every frame", "buttons: the last input mask", "box_x: moves by 2 with LEFT and RIGHT", "Because we know the source, every reading has a known answer"]),
    W("probe_update", L4, ["probe_update:", 23], E4, "Read input, store it, count a frame, move box_x. The screenshot: RIGHT held for 40 frames moved the box from 152 to 232."),
    H("Build and import", "Your own cartridge on a third host"),
    X("Build the probe", ["$ cd $PRG32_HOME", "$ python3 -m prg32 cartridge build ../Playing-with-RISC-V_PRG32_textbook/labs/04-prg32qt/probe.S --portable --entry-prefix probe --name probe --out work/probe.prg32", "Note code= from the log"], 3, "[OK] built ... code=2780 mem=2780."),
    X("Import and enable debug mode", ["In PRG32-QT import work/probe.prg32 and run it", "Move the box with the arrow keys; press Escape", "Settings: enable 'Run cartridges in RISC-V debug mode'", "Run it again"], 4, "A yellow box and a green bar growing along the top; then the same with the debugger panel beside it.", null, E4),
    H("The trampoline", "What the console really calls"),
    K("Select Update: this is not your code yet", "prg32_entry_update:\n    addi sp, sp, -16\n    sw   ra, 12(sp)\n    la   t0, __prg32_abi\n    sw   a0, 0(t0)        # the host passes the ABI table in a0\n    call probe_update     # now your function\n    lw   ra, 12(sp)\n    addi sp, sp, 16\n    ret", null,
      ["Generated by the cartridge builder", "It saves the table pointer for the stubs", "Then it calls your update"], "From prg32/cartridge/build_cartridge.py. The disassembly shows auipc/addi pairs for la and call."),
    X("Step into your function", ["Select the Update view and press Pause", "Step until the highlighted row enters probe_update", "Note pc, sp and ra", "Step once more (the addi sp): note sp again"], 6, "In the trampoline sp goes 0x40842000 -> 0x40841ff0; in probe_update it goes to 0x40841fe0. ra = 0x40800aa8, an address inside the trampoline: where probe_update must return."),
    K("A real trace of one update", "pc          instruction          what changed\n0x40800a90  c.addi sp, -16       sp = 0x40841ff0\n0x40800a94  la t0, __prg32_abi   t0 = 0x40800ad8\n0x40800a9c  sw a0, 0(t0)         saves 0x40840000\n0x40800aa0  call probe_update    ra = 0x40800aa8\n0x40800002  c.addi sp, -16       sp = 0x40841fe0\n0x40800006  call (the stub)      ra = 0x4080000e\n0x408000be  la t0 / lw t0        t0 = 0x40840000\n0x408000ca  lw t1, 24(t0)        t1 = 0xf0000004\n0x408000ce  c.jr t1              a0 = 0x0\n0x4080000e  la t0, buttons       t0 = 0x40800ad0", null,
      ["Rows 1-4: the trampoline saves the table pointer and calls you", "Rows 5-6: your prologue and your call", "Rows 7-9: the stub reads table entry 1 (offset 24) and jumps to the host", "a0 = 0: no key held"], "Recorded from PRG32-QT 0.4.1 through its /api/debug interface, single-stepping labs/04-prg32qt/probe.S."),
    Q("pc advanced by 2, not 4, after one step. Why?", ["A step was skipped", "The instruction has a 16-bit compressed encoding", "pc counts in half-words", "It was a branch"], 1, "RV32IMAC: the C extension encodes common instructions in 16 bits."),
    H("Input in a0", "A return value, seen in a register"),
    X("Break after the input call", ["In probe_update find the call to prg32_input_read", "Click the gutter beside the NEXT instruction (the la t0, buttons)", "Make sure the bug toggle is highlighted; press Resume", "It stops there once per frame"], 5, "Execution stops at 0x4080000e, immediately after the input read, once per frame: 'frames' is one higher at each stop."),
    X("Read the mask", ["No key held: Resume, read a0", "Hold LEFT, Resume, read a0", "Hold LEFT and Z, Resume, read a0", "Hold RIGHT, Resume, read a0"], 5, "0x00000000, 0x00000001, 0x00000011, 0x00000002.", "Input is frozen while paused: hold the key, then press Resume. The no-key reading was recorded from the real application; the key-held values follow from the button masks."),
    G("Explain the readings", ["Keys held", "a0", "Bits set"], [["none", "0x00", "-"], ["LEFT", "0x01", "bit 0"], ["LEFT + A", "0x11", "bits 0 and 4"], ["RIGHT", "0x02", "bit 1"]]),
    X("Follow the decision", ["With RIGHT held, step from the breakpoint to 'andi t3, a0, 1'", "Step it: read t3", "Step the beqz: did pc jump?", "Step on to 'andi t3, a0, 2' and its beqz"], 5, "t3 = 0 after the LEFT test, so the first beqz jumps over the addi. After the RIGHT test t3 = 2 and the second beqz falls through."),
    H("Memory", "Find a variable and watch it"),
    X("Get an address from a register", ["Step until just after 'la t0, box_x' in probe_update", "Read t0: this is the ADDRESS of box_x", "Type it in the memory field and press Inspect", "Read the first four bytes"], 6, "t0 = 0x40800ad4. The four bytes there are 98 00 00 00: 0x98 = 152, little-endian."),
    T("Reading a little-endian word", ["Memory shows bytes in address order", "RISC-V stores the least significant byte first", "98 00 00 00 is 0x00000098 = 152", "e8 00 00 00 is 0x000000e8 = 232", "04 01 00 00 would be 0x00000104 = 260"], null, ["98 00 00 00", "= 152"]),
    X("Watch it change", ["Remove the breakpoint; Resume", "Hold RIGHT for about a second; Pause", "Inspect the same address again", "Inspect 0x40800acc: frames, buttons, box_x are three consecutive words"], 5, "At 0x40800acc: frames (it grows by one per frame: 3b, 3c, 3d...), then buttons (0 when nothing is held), then box_x, which grew by 2 per frame held."),
    Q("box_x shows 'e8 00 00 00'. For how many frames was RIGHT held since 152?", ["232", "80", "40", "20"], 2, "(232 - 152) / 2 = 40."),
    H("Scripted control", "The debugger as an instrument"),
    X("Find the device and pause it", ["Read the device URL shown by PRG32-QT", "$ python3 -m prg32 runtime --url http://HOST:PORT", "$ python3 -m prg32 debug enable --url http://HOST:PORT", "$ python3 -m prg32 debug pause --url http://HOST:PORT"], 4, "JSON with \"firmware_version\": \"qt-0.4.1\", \"cart_abi_minor\": 6 and the loaded cartridge; then the game freezes."),
    X("Step and read from a script", ["$ python3 -m prg32 debug step --url http://HOST:PORT", "$ python3 -m prg32 debug state --url http://HOST:PORT", "Find pc and a0 in the reply", "$ python3 -m prg32 debug resume --url http://HOST:PORT"], 5, "Each step retires one instruction; state returns pc, paused, phase (update or draw), speed, breakpoints, the 32 registers and a memory dump as JSON."),
    T("Discussion", ["Which claim from the lecture did you verify with your own eyes?", "Why is the first code in Update not yours?", "What can this debugger not tell you about the real board?", "How would you automate a check that a function preserves s0?"]),
    N("You can now", ["Build and debug a cartridge in PRG32-QT", "Explain the entry trampoline", "Read a return value in a0 and follow a branch", "Take an address from a register and inspect memory", "Decode a little-endian word", "Drive the debugger from the command line"]),
  ],
  next: ["Assembly track: use this debugger in every lab", "Write up the a0 table and the box_x reading", "Read PRG32-QT docs/DEBUGGING.md"],
  refs: ["Textbook, Chapter 4", "labs/04-prg32qt/probe.S", "PRG32-QT docs/DEBUGGING.md", "PRG32 docs/software/api.md (debugger API)"] });

// ------------------------------------------------------------------ chapter 5
const L5 = "labs/05-asm-first-contact/", E5 = (s) => `${L5}expected/${s}.png`;
Deck({ n: 5, slug: "asm-first-contact", kind: "lab", title: "Assembly Lab 1: Hello, Stack Frame, Counter", short: "Registers, Memory, and the Call",
  subtitle: "Four verified steps, a hand trace, and three deliberate bugs with known symptoms",
  audience: ARCH, prep: "Working toolchain; PRG32-QT for the tracing step. Step files: labs/05-asm-first-contact/step1..4.",
  goals: ["Build an assembly cartridge that draws text", "Write a correct prologue and epilogue", "Keep state in .data and change it with load-modify-store", "Trace a sequence by hand and confirm it", "Diagnose a missing store, an unsaved ra and an unbalanced stack"],
  agenda: [["Skeleton and hello", 10], ["State and the counter", 12], ["Trace by hand", 8], ["Three bugs", 15]],
  slides: [
    HOW,
    T("A note on the console calls", ["The chapter's examples print with prg32_console_write", "On the board and in QEMU that text goes to the serial monitor", "PRG32-QT does not show it", "In this lab we draw text on the screen instead, so every host shows the same thing"]),
    H("Skeleton and hello", "Steps 1 and 2"),
    X("Step 1: three returns", [RUN("05-asm-first-contact/step1_skeleton.S", "first"), "Open the file: find .global and the three labels", "What does ret use to know where to go?"], 3, "A black screen, code=2604. ret jumps to the address in ra, which the caller's call put there.", null, E5("step1_skeleton")),
    W("Step 2: a frame, and five arguments", L5 + "step2_hello.S", ["first_draw:", 15], E5("step2_hello"), "Prologue: make 16 bytes, save ra. Body: two calls. Epilogue: restore ra, release, ret."),
    X("Run step 2", [RUN("05-asm-first-contact/step2_hello.S", "first"), "Change x to 120 and y to 96", "Change the string", "Swap the WHITE and BLACK arguments: which register is which?"], 5, "HELLO PRG32 in white at (32, 40). a3 is the foreground, a4 the background.", null, E5("step2_hello")),
    M("The 16-byte frame", [["(free)", 4, "sp + 0"], ["(free)", 4, "sp + 4"], ["(free, later s0)", 4, "sp + 8"], ["saved ra", 4, "sp + 12: sw ra, 12(sp)"]], "The stack grows downward: 'addi sp, sp, -16' reserves these 16 bytes. sp must stay a multiple of 16 at every call."),
    H("State and the counter", "Steps 3 and 4"),
    W("Step 3: load, modify, store", L5 + "step3_counter.S", ["first_update:", 7], E5("step3_counter"), "counter lives in .data. update is a leaf: it calls nothing, so it needs no frame. Nothing visible changes yet."),
    X("Run step 3, look inside", [RUN("05-asm-first-contact/step3_counter.S", "first"), "The screen looks like step 2: where is the counter?", "In PRG32-QT debug mode, step past 'la t0, counter' and read t0", "Inspect that address twice, a second apart"], 6, "The word at that address grows by about 30 per second: state changes even when nothing is drawn.", null, E5("step3_counter")),
    W("Step 4: draw the state", L5 + "step4_bar.S", ["call prg32_gfx_text8", 10], E5("step4_bar"), "A bar whose width is counter AND 255: it grows for 256 frames, then starts again. Screenshot taken at frame 100."),
    X("Run step 4", [RUN("05-asm-first-contact/step4_bar.S", "first"), "Time one full sweep of the bar", "Compute frames per second: 256 / seconds", "Change 'addi t1, t1, 1' to 'addi t1, t1, 4'"], 5, "One sweep takes about 8.5 seconds at 30 frames per second; with 4 it sweeps four times faster.", null, E5("step4_bar")),
    Q("Why 'andi a2, t1, 255' and not the counter itself as width?", ["rect cannot take a register", "The counter grows without bound; AND keeps the low 8 bits, 0..255", "andi is faster than mv", "To convert to hexadecimal"], 1, "A bit mask as a cheap modulo by a power of two."),
    H("Trace by hand", "Be the processor"),
    X("Fill in the table", ["Take the four lines of first_update", "Assume counter is at 0x40800a90 and holds 20", "One row per instruction: t0 after, t1 after, memory after", "Which instruction changes memory?"], 5, "la: t0 = 0x40800a90. lw: t1 = 20. addi: t1 = 21. sw: memory = 21. Only sw changes memory."),
    G("The answer", ["Instruction", "t0", "t1", "Memory"], [["la t0, counter", "0x40800a90", "?", "20"], ["lw t1, 0(t0)", "0x40800a90", "20", "20"], ["addi t1, t1, 1", "0x40800a90", "21", "20"], ["sw t1, 0(t0)", "0x40800a90", "21", "21"]], "The address is an example; yours is whatever t0 showed in step 3."),
    H("Three bugs", "Each has a symptom you will meet again"),
    X("Bug 1: the missing store", ["In a copy of step4_bar.S delete 'sw t1, 0(t0)' in update", "Predict the picture", "Build and run"], 4, "HELLO PRG32 and no bar, forever: the incremented value never leaves the register. The picture is exactly step 3's.", null, E5("step3_counter")),
    X("Bug 2: the unsaved ra", ["Restore; now delete 'sw ra, 12(sp)' and 'lw ra, 12(sp)' in draw", "Predict what ret does", "Run in PRG32-QT"], 4, "The first frame never ends. PRG32-QT reports 'instruction budget exhausted'; QEMU and the board simply hang.", "Verified with the headless runner: 'frame 0: instruction budget exhausted'."),
    X("Bug 3: the unbalanced stack", ["Restore; now change the epilogue to 'addi sp, sp, 8'", "Predict: a slow leak, or an immediate failure?", "Run in PRG32-QT"], 4, "Immediate failure: 'instruction fetch outside cartridge memory'. Your caller, the trampoline, reloads ITS ra from 12(sp), now the wrong slot, and jumps to garbage.", "Verified with the headless runner. Students usually predict a slow leak: the caller's frame is what breaks."),
    G("Symptoms to remember", ["Symptom", "Cause"], [["Value never changes", "Missing sw after modifying a register"], ["Hangs in the first frame", "ra not saved before a call"], ["Crashes at the first return", "sp not restored exactly"], ["Works, then corrupts later", "An s register used but not saved"]], null, [1.2, 2]),
    N("You can now", ["Run and modify an assembly cartridge", "Write a frame without looking", "Keep and change state in .data", "Trace load-modify-store", "Name three bugs by their symptoms"]),
  ],
  next: ["Read Chapter 6: branches and input", "Write up Bug 3: why did it fail at once?", "Keep your copy of step4_bar.S"],
  refs: ["Textbook, Chapter 5", "labs/05-asm-first-contact/ in the textbook repository", "PRG32 docs/learn/labs/lab_01_hello_world.md and debugging_register_tracing.md"] });

// ------------------------------------------------------------------ chapter 6
const L6 = "labs/06-asm-state-and-input/", E6 = (s) => `${L6}expected/${s}.png`;
Deck({ n: 6, slug: "asm-state-and-input", kind: "lab", title: "Assembly Lab 2: A Marker You Can Steer", short: "Branches, Bitmasks, Boundaries",
  subtitle: "See the input bits as lamps, move a marker, clamp it, add a second axis: four verified steps",
  audience: ARCH, prep: "Working toolchain; PRG32-QT for the proof step. Step files: labs/06-asm-state-and-input/step1..4.",
  goals: ["Display the input bitmask one bit per lamp", "Move state with independent button tests", "Clamp to exact limits and test the edges", "Repeat the pattern on a second axis", "Explain which registers survive a call"],
  agenda: [["Lamps: see the bits", 11], ["Move", 10], ["Clamp", 10], ["Second axis", 8], ["Bug hunt", 6]],
  slides: [
    HOW,
    H("Lamps", "Step 1: see the bits before you use them"),
    W("Step 1: one lamp per bit", L6 + "step1_lamps.S", ["# Seven lamps", 18], E6("step1_lamps"), "A loop: s0 is the bit number. srl moves that bit down to position 0, andi keeps it. Screenshot: RIGHT and A held (0x12)."),
    X("Run step 1", [RUN("06-asm-state-and-input/step1_lamps.S", "steer"), "Hold each button alone: which lamp lights?", "Hold LEFT and A together", "Fill in a table: button, lamp number, mask value"], 6, "Lamp 0 LEFT, 1 RIGHT, 2 UP, 3 DOWN, 4 A, 5 B, 6 START. Mask = 1 shifted left by the lamp number.", null, E6("step1_lamps")),
    T("Why s0, and why it is saved", ["The loop counter must survive seven calls to prg32_gfx_rect", "t and a registers may be destroyed by any call", "s registers are preserved by the callee", "So WE must preserve s0 for OUR caller: sw s0, 8(sp) in the prologue"]),
    Q("Lamps 1 and 4 are lit. What did prg32_input_read return?", ["0x05", "0x12", "0x14", "0x21"], 1, "bit 1 (2) + bit 4 (16) = 18 = 0x12."),
    H("Move", "Step 2: input changes state"),
    W("Step 2: LEFT and RIGHT move x", L6 + "step2_move.S", ["la   t1, marker_x", 9], E6("step2_move"), "Load x once, adjust it through both tests, store it once. Each test: andi isolates the bit, beqz skips when clear."),
    X("Run step 2", [RUN("06-asm-state-and-input/step2_move.S", "steer"), "Hold RIGHT: the marker moves 2 pixels per frame", "Hold LEFT and RIGHT together: what happens, and why?", "Change SPEED to 6"], 5, "The marker follows the keys (screenshot: RIGHT for 40 frames, x = 232). With both held the two adjustments cancel.", null, E6("step2_move")),
    X("Prove it in the debugger", ["Import the step 2 cartridge into PRG32-QT, debug mode", "Breakpoint on 'andi t3, t0, BTN_LEFT' in steer_update", "Hold RIGHT, Resume, then step to the sw", "Record t0, t2 before and after the addi"], 5, "t0 = 2; t3 = 0 then 2; t2 increases by exactly 2; the sw writes it back."),
    X("See the problem", ["Hold RIGHT for five seconds", "Where is the marker now?", "Hold LEFT until it comes back: how long?"], 3, "Off the screen: marker_x keeps growing past 320. It returns only after you undo every step."),
    H("Clamp", "Step 3: stay on the screen"),
    W("Step 3: a two-sided clamp", L6 + "step3_clamp.S", ["bgez t2, 3f", 6], E6("step3_clamp"), "Below zero: replace by 0. Above 304: replace by 304. Inserted between the tests and the single store."),
    X("Run step 3 and test the edges", [RUN("06-asm-state-and-input/step3_clamp.S", "steer"), "Hold RIGHT until it stops", "In PRG32-QT read marker_x from memory at each edge", "Why 304?"], 5, "The marker stops flush with the right edge (screenshot: RIGHT for 120 frames). Memory shows 0 and 0x130 = 304 = 320 - 16.", null, E6("step3_clamp")),
    X("An off-by-one, on purpose", ["Change 'ble t2, t3, 4f' to 'blt t2, t3, 4f'", "Predict: does the behaviour change at exactly 304?", "Run and check; then restore"], 4, "No visible change: at exactly 304 the value is replaced by 304. Boundary conditions deserve a test, even when both versions happen to work."),
    Q("A 24-pixel-wide marker: which MAX_X?", ["320", "304", "296", "344"], 2, "320 - 24."),
    H("Second axis", "Step 4: the same pattern again"),
    W("Step 4: UP and DOWN", L6 + "step4_two_axes.S", ["la   t1, marker_y", 14], E6("step4_two_axes"), "Same shape with masks 4 and 8 and limits 60..184. UP subtracts: a smaller y is higher on the screen."),
    X("Run step 4", [RUN("06-asm-state-and-input/step4_two_axes.S", "steer"), "Move to all four corners of the allowed area", "Which instruction makes UP go up?", "Change MIN_Y to 0: what does the marker cover?"], 5, "The marker stops at each limit (screenshot: RIGHT and DOWN for 80 frames, bottom-right corner). addi t2, t2, -SPEED moves up.", null, E6("step4_two_axes")),
    T("Notice the repetition", ["x and y use the same instructions with different masks and limits", "In C you would write one function", "In assembly too: value in a0, limits in a1 and a2, result in a0", "A leaf function like that needs no frame"]),
    H("Bug hunt", "A planted fault: find it with evidence"),
    K("This update has one bug", "    call prg32_input_read\n    la   t1, marker_x\n    lw   t2, 0(t1)\n    andi t3, a0, 1\n    beqz t3, 1f\n    addi t2, t2, -2\n1:  call prg32_ticks_ms          # someone added this\n    andi t3, a0, 2\n    beqz t3, 2f\n    addi t2, t2, 2\n2:  sw   t2, 0(t1)", null, ["LEFT works", "RIGHT does not", "Sometimes x becomes garbage"]),
    X("Find it", ["Which registers are still needed after the second call?", "State a hypothesis in one sentence", "Which breakpoint and register would confirm it?", "Write the fix"], 5, "a0, t1 and t2 are used after a call that may destroy all three. Fix: keep the input in an s register saved in the frame, as step 1 does with s0."),
    N("You can now", ["Read the input mask bit by bit", "Move state with andi and beqz", "Clamp to computed limits", "Reuse a pattern on a second axis", "Say which registers survive a call"]),
  ],
  next: ["Read Chapter 7: graphics and collision", "Optional: write clamp as a leaf function", "The next lab reuses the move-and-clamp pattern for a paddle"],
  refs: ["Textbook, Chapter 6", "labs/06-asm-state-and-input/ in the textbook repository", "PRG32 docs/learn/labs/lab_02_input.md"] });

// ------------------------------------------------------------------ chapter 7
const L7 = "labs/07-asm-graphics-game/", E7 = (s) => `${L7}expected/${s}.png`;
Deck({ n: 7, slug: "asm-graphics-game", kind: "lab", title: "Assembly Lab 3: Pong in Six Steps", short: "Graphics, Collision, and the Frame",
  subtitle: "Blank frame, paddle, movement, ball, bounces, collision: build, run and verify after every step",
  audience: ARCH, prep: "Working toolchain. Step files: labs/07-asm-graphics-game/step1..6 (one master, labs/masters/pong.master.S).",
  goals: ["Draw a frame from state", "Move and clamp a paddle in pixels", "Animate a ball with velocity and wall bounces", "Add a guarded paddle collision", "Verify each step before starting the next"],
  agenda: [["Frame and paddle", 9], ["Moving paddle", 8], ["Ball", 12], ["Collision", 11], ["Tune", 5]],
  slides: [
    HOW,
    H("Frame and paddle", "Steps 1 and 2"),
    W("Step 1: a blank frame", L7 + "step1_blank.S", ["pong_draw:", 9], E7("step1_blank"), "draw calls a helper, so it has a frame. One argument: the colour, in a0."),
    W("Step 2: the paddle, from state", L7 + "step2_paddle.S", ["# --- paddle: prg32_gfx_rect", 8], E7("step2_paddle"), "x is loaded from memory; y, width, height and colour are .equ constants. paddle_x starts at 128."),
    X("Run steps 1 and 2", [RUN("07-asm-graphics-game/step1_blank.S", "pong"), RUN("07-asm-graphics-game/step2_paddle.S", "pong"), "Change the initial paddle_x to 0, then 256, then 300", "Change PADDLE_W to 32"], 6, "A white bar at the bottom. At 300 it hangs off the right edge: nothing stops state from holding an illegal value.", null, E7("step2_paddle")),
    Q("Which register carries the rectangle's width?", ["a0", "a1", "a2", "a3"], 2, "x a0, y a1, w a2, h a3, colour a4."),
    H("Moving paddle", "Step 3"),
    W("Step 3: move and clamp", L7 + "step3_move.S", ["# --- paddle: move with", 14], E7("step3_move"), "The pattern of Lab 2, in pixels: 4 per frame, clamped to 0..256. update now needs a frame because it calls."),
    X("Run step 3", [RUN("07-asm-graphics-game/step3_move.S", "pong"), "Hold RIGHT to the edge: is the paddle flush?", "In PRG32-QT read paddle_x at both ends", "Change PADDLE_W to 32 only: what goes wrong?"], 6, "The paddle stops at x = 256 = 0x100 (screenshot: RIGHT for 30 frames, x = 248). With width 32 it stops 32 pixels short: PADDLE_MAX must change too.", null, E7("step3_move")),
    H("Ball", "Steps 4 and 5"),
    W("Step 4: horizontal motion", L7 + "step4_ball_x.S", ["# --- ball x", 14], E7("step4_ball_x"), "x = x + dx. At each wall: clamp to the edge AND negate dx. 312 = 320 - 8."),
    X("Run step 4", [RUN("07-asm-graphics-game/step4_ball_x.S", "pong"), "Time one crossing", "Check: 312 pixels at 2 per frame at 30 frames per second", "Remove the two clamp lines (li t2, 0 and mv t2, t5): does it still bounce?"], 5, "About 5.2 seconds per crossing. Without the clamps it still bounces, but can sit one step outside the screen for a frame.", null, E7("step4_ball_x")),
    W("Step 5: vertical motion", L7 + "step5_ball_y.S", ["# --- ball y", 10], E7("step5_ball_y"), "The same pattern on y, but only the top bounces. The bottom is the paddle's job."),
    X("Run step 5", [RUN("07-asm-graphics-game/step5_ball_y.S", "pong"), "Watch the ball reach the bottom", "Where is it ten seconds later?", "Read ball_y in PRG32-QT"], 4, "The ball leaves through the bottom and never returns: ball_y keeps growing. State goes on changing off screen.", null, E7("step5_ball_y")),
    H("Collision", "Step 6"),
    W("Step 6: eight arguments, one answer", L7 + "step6_collision.S", ["# --- paddle collision", 19], E7("step6_collision"), "Ball in a0-a3, paddle in a4-a7, answer in a0. blez is the guard: bounce only while moving down."),
    K("Step 6: the lost ball", L7 + "step6_collision.S", ["# --- lost ball", 6], ["t2 still holds the new ball_y", "Past 200: put it back at y = 40", "t1 still holds the address of ball_y"]),
    X("Run step 6", [RUN("07-asm-graphics-game/step6_collision.S", "pong"), "Keep the ball alive for ten bounces", "Miss on purpose: where does it restart?", "Count instructions between the hitbox call and update_done"], 6, "A playable game (screenshot: frame 150, the ball on the paddle). A missed ball reappears at y = 40.", null, E7("step6_collision")),
    X("Remove the guard", ["Delete the 'blez t1, update_done' line", "Move the paddle INTO the falling ball from the side", "Describe what you see; then restore"], 4, "The ball can jitter inside the paddle or pass through: it overlaps for several frames and is negated on each."),
    Q("With the guard removed, a ball overlapping for exactly 2 frames leaves moving...", ["Up", "Down: negated twice", "Sideways", "It stops"], 1, "Two negations restore the original direction."),
    H("Tune", "Make it feel right"),
    X("One parameter at a time", ["PADDLE_SPEED: try 2 and 8", "ball_dx 3, ball_dy 2", "PADDLE_W 32: which other line must change?", "Write down the values you prefer"], 5, "A different game for each value. Thanks to .equ, the width is one edit plus PADDLE_MAX; the hitbox follows automatically."),
    T("What the file contains now", ["139 lines; 2984 bytes of cartridge", "Five words of state: paddle_x, ball_x, ball_y, ball_dx, ball_dy", "update: input, paddle, ball x, ball y, lost ball, collision", "draw: clear, paddle, ball", "Nothing is drawn in update; nothing changes in draw"], null, ["20 bytes", "of state for a whole game"]),
    N("You can now", ["Draw a frame from state", "Animate with velocity and bounces", "Call a function with eight arguments", "Guard a collision so it happens once", "Build a game in verified increments"]),
  ],
  next: ["Read Chapter 8: the capstone", "The next lab continues from step 6", "Keep your tuned copy"],
  refs: ["Textbook, Chapter 7", "labs/07-asm-graphics-game/ and labs/masters/pong.master.S", "Appendix C: Pong in graphics assembly"] });

// ------------------------------------------------------------------ chapter 8
const L8 = "labs/08-asm-capstone/", E8 = (s) => `${L8}expected/${s}.png`;
Deck({ n: 8, slug: "asm-capstone", kind: "lab", title: "Assembly Lab 4: Extend It, Sound It, Ship It", short: "Assembly Capstone",
  subtitle: "Score, an event sound, a pause on a button edge, then a cartridge on two hosts: steps 7 to 9",
  audience: ARCH, prep: "Continues Lab 3. Step files: labs/08-asm-capstone/step7..9. PRG32-QT for the edge proof; a board per bench if available.",
  goals: ["Add a feature as state, rule and picture", "Keep a counter honest with a guard", "Play a mixer note on an event", "Tell a button level from a button edge", "Build, inspect and deliver a cartridge"],
  agenda: [["Score", 12], ["Sound", 8], ["Pause on an edge", 13], ["Ship and review", 12]],
  slides: [
    HOW,
    S("Every feature is three edits", [["State", "A new word in .data."], ["Rule", "Lines in update that change it."], ["Picture", "Lines in draw that show it."]], "Score: score / +1 in the guarded bounce / a bar. Pause: paused and previous_input / toggle on the edge of A / the frozen game itself."),
    H("Score", "Step 7"),
    W("Step 7: the rule, inside the guard", L8 + "step7_score.S", ["blez t1, update_done", 8], E8("step7_score"), "The increment sits after the blez guard, so it runs exactly once per bounce. Load, add 1, store."),
    W("Step 7: the picture", L8 + "step7_score.S", ["# --- score: a bar", 12], E8("step7_score"), "Width = score shifted left by 2 (times 4), clamped to 312 so the bar can never leave the screen."),
    X("Run step 7", [RUN("08-asm-capstone/step7_score.S", "pong"), "Score five points: the bar is 20 pixels long", "Read score in PRG32-QT memory after each bounce", "Change slli a2, t1, 2 to slli a2, t1, 4"], 6, "+1 per bounce, never +2. With a shift of 4 each point is 16 pixels and the clamp at 312 matters after 19 points.", null, E8("step7_score")),
    Q("Why slli by 2 rather than mul by 4?", ["mul is not available", "A shift is the idiomatic one-instruction multiply by a power of two", "mul needs a frame", "slli is more precise"], 1, "Both work on RV32IM; the shift needs no second register."),
    H("Sound", "Step 8"),
    W("Step 8: a note on the event", L8 + "step8_sound.S", ["li   a0, 0                 # channel", 6], E8("step8_sound"), "Five arguments; the call returns at once and the mixer plays the note. It sits after the score update on purpose."),
    X("Run step 8", [RUN("08-asm-capstone/step8_sound.S", "pong"), "Listen: one note per bounce", "Change note 72 to 60, then 84", "Why may the six sound lines NOT go between the lw and the sw of the score update?"], 6, "A C5 at each paddle hit. Between lw and sw the call would sit while t0 and t1 are live: caller-saved registers are not guaranteed to survive a call.", "Reasoning question: on some hosts the registers happen to survive, which is exactly why this bug is dangerous.", E8("step8_sound")),
    G("prg32_audio_note in registers", ["Register", "Argument", "Here"], [["a0", "channel, 0-7", "0"], ["a1", "instrument", "0 (default)"], ["a2", "MIDI note", "72 = C5"], ["a3", "volume, 0-255", "255"], ["a4", "duration, ms", "60"]]),
    H("Pause", "Step 9: an edge, not a level"),
    V("Level and edge", ["Level: is A down?", ["input AND mask", "True on every frame it is held", "A toggle on a level flickers 30 times a second"]], ["Edge: did A just go down?", ["input AND NOT previous AND mask", "True for one frame per press", "One press, one toggle"]]),
    W("Step 9: detecting the edge", L8 + "step9_pause.S", ["# --- pause", 17], E8("step9_pause"), "s0 keeps the input across calls. not + and gives the newly pressed bits. xori flips paused between 0 and 1."),
    X("Run step 9", [RUN("08-asm-capstone/step9_pause.S", "pong"), "Press A once: the game freezes. Again: it resumes", "Hold A down for two seconds: how many toggles?", "Why is input read into s0 and not kept in a0?"], 6, "One toggle per press however long A is held (screenshot: paused by one press at frame 100).", null, E8("step9_pause")),
    X("Prove it", ["In PRG32-QT, breakpoint on the xori", "Hold Z and press Resume twice", "How many times does it stop?", "Now change 'and t1, s0, t1' to 'mv t1, s0' and repeat"], 5, "Once per press. With the level instead of the edge it stops on every frame while Z is held."),
    Q("previous = 0x10, input = 0x11. Newly pressed?", ["A", "LEFT", "LEFT and A", "Nothing"], 1, "0x11 AND NOT 0x10 = 0x01."),
    H("Ship and review", "A file someone else can run"),
    X("Build and inspect by hand", ["$ cd $PRG32_HOME", "$ python3 -m prg32 cartridge build ../Playing-with-RISC-V_PRG32_textbook/labs/08-asm-capstone/step9_pause.S --portable --entry-prefix pong --name my-pong --out work/my-pong.prg32", "$ python3 -m prg32 cartridge summary work/my-pong.prg32"], 5, "code=3160 mem=3160; import_model abi-table; header_size 100. About 560 bytes are your game; the rest is stubs."),
    X("Two hosts", ["$ python3 -m prg32 qemu upload work/my-pong.prg32 && python3 -m prg32 qemu run", "Import the same file into PRG32-QT", "Board: python3 -m prg32 esp32c6 upload work/my-pong.prg32 --url http://192.168.4.1"], 5, "Identical behaviour everywhere: the file does not know which host runs it."),
    X("Swap and review", ["Give your .prg32, not the source, to another pair", "Play theirs for two minutes; try the edges", "Write one defect and one thing you liked", "Return the note"], 5, "A short, concrete review from players who never saw your code."),
    T("From here to the capstone", ["You have the loop: design, build, debug, ship, review", "Pick one mechanic and write its state-rule-picture table", "Keep every counter inside a guard", "Chapter 17 publishes the result"]),
    N("You can now", ["Add a feature as three edits", "Guard a counter", "Play notes on events without clobbering registers", "Implement and prove edge detection", "Ship and review a cartridge"]),
  ],
  next: ["Write your capstone proposal with a state-rule-picture table", "Read Chapter 16", "Optional: prepare a Store bundle (Chapter 17)"],
  refs: ["Textbook, Chapter 8", "labs/08-asm-capstone/ and labs/masters/pong.master.S", "PRG32 docs/learn/labs/lab_04_sound.md"] });
