/*
 * Generated by PRG32-Construction-Kit.
 * Edit the blocks or project JSON, then regenerate this file.
 */
#include <stdint.h>
#include "prg32.h"

#ifndef PRG32_COLOR_BLACK
#define PRG32_COLOR_BLACK 0x0000
#endif
#ifndef PRG32_COLOR_WHITE
#define PRG32_COLOR_WHITE 0xFFFF
#endif
#ifndef PRG32_COLOR_RED
#define PRG32_COLOR_RED 0xF800
#endif
#ifndef PRG32_COLOR_GREEN
#define PRG32_COLOR_GREEN 0x07E0
#endif
#ifndef PRG32_COLOR_BLUE
#define PRG32_COLOR_BLUE 0x001F
#endif
#ifndef PRG32_COLOR_YELLOW
#define PRG32_COLOR_YELLOW 0xFFE0
#endif
#ifndef PRG32_COLOR_CYAN
#define PRG32_COLOR_CYAN 0x07FF
#endif
#ifndef PRG32_COLOR_MAGENTA
#define PRG32_COLOR_MAGENTA 0xF81F
#endif
#ifndef PRG32_COLOR_ORANGE
#define PRG32_COLOR_ORANGE 0xFD20
#endif
#ifndef PRG32_COLOR_PINK
#define PRG32_COLOR_PINK 0xF81F
#endif

/* Convert a classroom frequency to the nearest supported MIDI note. */
static uint8_t prg32_kit_note_from_hz(int hz) {
    static const uint16_t frequencies[] = {
        131, 139, 147, 156, 165, 175, 185, 196, 208, 220, 233, 247,
        262, 277, 294, 311, 330, 349, 370, 392, 415, 440, 466, 494,
        523, 554, 587, 622, 659, 698, 740, 784, 831, 880, 932, 988, 1047
    };
    unsigned int index;
    if (hz <= frequencies[0]) return 48;
    for (index = 0; index < 36; ++index) {
        if (hz < (frequencies[index] + frequencies[index + 1]) / 2) return (uint8_t)(48 + index);
    }
    return 84;
}

static int basket_x = 144;
static int lemon_x = 150;
static int lemon_y = 0;
static int score = 0;
static int misses = 0;

void lemon_catcher_init(void) {
    basket_x = 144;
    lemon_x = 150;
    lemon_y = 0;
    score = 0;
    misses = 0;
    basket_x = 144;
    lemon_x = 150;
    lemon_y = 0;
    score = 0;
    misses = 0;
}

void lemon_catcher_update(void) {
    uint32_t input = prg32_input_read();
    if (input & PRG32_BTN_LEFT) {
        basket_x += -4;
    }
    if (input & PRG32_BTN_RIGHT) {
        basket_x += 4;
    }
    if (basket_x < 0) { basket_x = 0; }
    if (basket_x > 288) { basket_x = 288; }
    /* The lemon falls a little every frame */
    lemon_y += 2;
    /* Caught: one point, a happy beep, a new lemon */
    if (prg32_sprite_hitbox(lemon_x, lemon_y, 10, 10, basket_x, 180, 32, 8)) {
        score += 1;
        prg32_audio_note(0, 0, prg32_kit_note_from_hz(880), 255, 80);
        lemon_y = 0;
        lemon_x = (int)prg32_random_number(0, 310);
    }
    /* Missed: the lemon touched the floor */
    if (prg32_sprite_hitbox(lemon_x, lemon_y, 10, 10, 0, 196, 320, 4)) {
        misses += 1;
        prg32_audio_note(0, 0, prg32_kit_note_from_hz(220), 255, 150);
        lemon_y = 0;
        lemon_x = (int)prg32_random_number(0, 310);
    }
    if (score < 0) { score = 0; }
    if (score > 75) { score = 75; }
    if (misses < 0) { misses = 0; }
    if (misses > 75) { misses = 75; }
}

void lemon_catcher_draw(void) {
    prg32_gfx_clear(PRG32_COLOR_BLACK);
    prg32_gfx_text8(8, 4, "LEMONS", PRG32_COLOR_GREEN, PRG32_COLOR_BLACK);
    prg32_gfx_rect(64, 4, score * 3, 8, PRG32_COLOR_GREEN);
    prg32_gfx_text8(8, 16, "MISSED", PRG32_COLOR_RED, PRG32_COLOR_BLACK);
    prg32_gfx_rect(64, 16, misses * 3, 8, PRG32_COLOR_RED);
    prg32_gfx_rect(lemon_x, lemon_y, 10, 10, PRG32_COLOR_YELLOW);
    prg32_gfx_rect(basket_x, 180, 32, 8, PRG32_COLOR_ORANGE);
    prg32_gfx_rect(0, 196, 320, 4, PRG32_COLOR_BLUE);
}
