/*
 * Generated by PRG32-Construction-Kit.
 * Edit the blocks or project JSON, then regenerate this file.
 */
#include <stdint.h>
#include "prg32.h"

#ifndef PRG32_COLOR_BLACK
#define PRG32_COLOR_BLACK 0x0000
#endif
#ifndef PRG32_COLOR_WHITE
#define PRG32_COLOR_WHITE 0xFFFF
#endif
#ifndef PRG32_COLOR_RED
#define PRG32_COLOR_RED 0xF800
#endif
#ifndef PRG32_COLOR_GREEN
#define PRG32_COLOR_GREEN 0x07E0
#endif
#ifndef PRG32_COLOR_BLUE
#define PRG32_COLOR_BLUE 0x001F
#endif
#ifndef PRG32_COLOR_YELLOW
#define PRG32_COLOR_YELLOW 0xFFE0
#endif
#ifndef PRG32_COLOR_CYAN
#define PRG32_COLOR_CYAN 0x07FF
#endif
#ifndef PRG32_COLOR_MAGENTA
#define PRG32_COLOR_MAGENTA 0xF81F
#endif
#ifndef PRG32_COLOR_ORANGE
#define PRG32_COLOR_ORANGE 0xFD20
#endif
#ifndef PRG32_COLOR_PINK
#define PRG32_COLOR_PINK 0xF81F
#endif

/* Convert a classroom frequency to the nearest supported MIDI note. */
static uint8_t prg32_kit_note_from_hz(int hz) {
    static const uint16_t frequencies[] = {
        131, 139, 147, 156, 165, 175, 185, 196, 208, 220, 233, 247,
        262, 277, 294, 311, 330, 349, 370, 392, 415, 440, 466, 494,
        523, 554, 587, 622, 659, 698, 740, 784, 831, 880, 932, 988, 1047
    };
    unsigned int index;
    if (hz <= frequencies[0]) return 48;
    for (index = 0; index < 36; ++index) {
        if (hz < (frequencies[index] + frequencies[index + 1]) / 2) return (uint8_t)(48 + index);
    }
    return 84;
}

static int paddle_x = 136;

void breakout_init(void) {
    paddle_x = 136;
    paddle_x = 136;
}

void breakout_update(void) {
    uint32_t input = prg32_input_read();
    if (input & PRG32_BTN_LEFT) {
        paddle_x += -4;
    }
    if (input & PRG32_BTN_RIGHT) {
        paddle_x += 4;
    }
    if (paddle_x < 0) { paddle_x = 0; }
    if (paddle_x > 272) { paddle_x = 272; }
}

void breakout_draw(void) {
    prg32_gfx_clear(PRG32_COLOR_BLACK);
    prg32_gfx_rect(paddle_x, 188, 48, 6, PRG32_COLOR_CYAN);
}
